ALTER TYPE "WarPlanViolationType" ADD VALUE IF NOT EXISTS 'TRADITIONAL_INVALID_CLEANUP_TARGET';
ALTER TYPE "WarPlanViolationType" ADD VALUE IF NOT EXISTS 'TRADITIONAL_UNCLEARED_MIRROR';

ALTER TABLE "WarPlanComplianceEvaluation"
ADD COLUMN "traditionalRequireMirrorAfterOpen" BOOLEAN;
