#!/usr/bin/env bash
set -euo pipefail

branch="$(git branch --show-current)"
base_branch="${PR_BASE_BRANCH:-dev}"
pr_body_file=".git/AI_PR_BODY.md"

if [ ! -f ".git/AI_COMMIT_MSG" ]; then
  echo "Missing .git/AI_COMMIT_MSG. Generate and save a Conventional Commit message first."
  exit 1
fi

if [ -z "$(git status --porcelain)" ]; then
  echo "No changes to commit."
  exit 1
fi

# Build a PR body from the current branch diff vs base branch.
git fetch origin "$base_branch" >/dev/null 2>&1 || true
merge_base="$(git merge-base "origin/$base_branch" HEAD 2>/dev/null || true)"
if [ -n "$merge_base" ]; then
  commits="$(git log --reverse --pretty=format:'- %s (%h)' "$merge_base..HEAD" || true)"
  changed_files_raw="$(git diff --name-only "$merge_base..HEAD" || true)"
else
  commits="$(git log --reverse --pretty=format:'- %s (%h)' -n 5 || true)"
  changed_files_raw="$(git show --pretty='' --name-only HEAD || true)"
fi

if [ -z "${commits}" ]; then
  commits="- $(head -n 1 .git/AI_COMMIT_MSG) ($(git rev-parse --short HEAD))"
fi

changed_file_count="$(printf "%s\n" "$changed_files_raw" | sed '/^$/d' | wc -l | tr -d ' ')"
changed_files="$(printf "%s\n" "$changed_files_raw" | sed '/^$/d' | head -n 30 | sed 's/^/- /')"
if [ -z "${changed_files}" ]; then
  changed_files="- No tracked file changes detected."
fi

{
  echo "## Summary"
  echo "- Auto-generated by \`scripts/commit-feature.sh\`."
  echo "- Branch: \`$branch\`"
  echo "- Base: \`$base_branch\`"
  echo
  echo "## Commit Notes"
  printf "%s\n" "$commits"
  echo
  echo "## Changed Files"
  printf "%s\n" "$changed_files"
  if [ "${changed_file_count:-0}" -gt 30 ]; then
    echo "- ...and $((changed_file_count - 30)) more file(s)."
  fi
} > "$pr_body_file"

git add -A
git commit -F .git/AI_COMMIT_MSG
git push -u origin HEAD

echo "Committed and pushed $(git branch --show-current)"

# Attempt to create/update PR description if GitHub CLI is available.
if ! command -v gh >/dev/null 2>&1; then
  echo "GitHub CLI not found. PR description body saved to $pr_body_file"
  exit 0
fi

if ! gh auth status >/dev/null 2>&1; then
  echo "GitHub CLI is not authenticated. PR description body saved to $pr_body_file"
  exit 0
fi

if pr_number="$(gh pr view --head "$branch" --json number --jq .number 2>/dev/null)"; then
  if [ -n "$pr_number" ]; then
    if gh pr edit "$pr_number" --body-file "$pr_body_file" >/dev/null 2>&1; then
      echo "Updated PR #$pr_number description from $pr_body_file"
      exit 0
    fi
  fi
fi

pr_title="$(head -n 1 .git/AI_COMMIT_MSG)"
if gh pr create \
  --base "$base_branch" \
  --head "$branch" \
  --title "$pr_title" \
  --body-file "$pr_body_file" >/dev/null 2>&1; then
  pr_url="$(gh pr view --head "$branch" --json url --jq .url 2>/dev/null || true)"
  if [ -n "$pr_url" ]; then
    echo "Created PR: $pr_url"
  else
    echo "Created PR for $branch"
  fi
  exit 0
fi

echo "Could not create/update PR via GitHub CLI. PR description body saved to $pr_body_file"
